"""Invoice PDF rendering via Typst (Rust-backed, deterministic, typographic-grade).

The Typst compiler is shipped as a Python wheel (`typst-py`), so no system install
is needed and the rendering path is fully reproducible. Every PDF carries an audit
hash in the footer for tamper-evidence.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import typst

from ..config import STAGING_DIR

BRAND_HEX = "#d9531e"  # TASC orange-red

# ponytail: emitting Typst source by string templating — safer than ad-hoc DSL,
# upgrade path is a sidecar .typ template file if the layout grows.

_MARKUP_SPECIALS = ("\\", "#", "*", "_", "`", "$", "<", ">", "[", "]", "~", "@")


def _esc(s) -> str:
    """Escape a value for Typst markup (plain text, no formatting)."""
    s = "" if s is None else str(s)
    for ch in _MARKUP_SPECIALS:
        s = s.replace(ch, "\\" + ch)
    return s


def _num(x) -> str:
    try:
        return f"{float(x):.2f}"
    except (TypeError, ValueError):
        return "0.00"


def _audit_hash(invoice: dict) -> str:
    payload = json.dumps(invoice, sort_keys=True, default=str).encode()
    return hashlib.sha256(payload).hexdigest()[:16]


_TEMPLATE = r"""
#set document(title: "TASC Invoice " + "{inv_id}")
#set page(paper: "a4", margin: (x: 1.6cm, y: 1.6cm))
#set text(size: 10pt, font: ("DejaVu Sans", "Liberation Sans", "Arial"))
#let brand = rgb("{brand}")
#let muted = rgb("#666666")
#let row_fill = (_, row) => if row == 0 {{ rgb("#ececec") }} else {{ none }}

#block(fill: brand, inset: (x: 14pt, y: 12pt), width: 100%, radius: 2pt)[
  #set text(fill: white, size: 18pt, weight: "bold")
  TASC Outsourcing #h(6pt) #text(size: 14pt, weight: "regular")[— Tax Invoice]
]

#v(10pt)

#grid(columns: (1fr, 1fr), gutter: 8pt,
  [
    *Invoice* \ {inv_id}
  ],
  [
    *Client* \ {client}
  ],
  [
    *Period* \ {period}
  ],
  [
    *Currency* \ AED
  ],
)

#v(12pt)

#table(
  columns: (1.6cm, 1fr, 1cm, 2cm, 1.6cm, 1.8cm, 2.3cm),
  align: (left, left, right, right, right, right, right),
  stroke: 0.4pt + rgb("#cccccc"),
  fill: row_fill,
  table.header(
    [*Emp ID*], [*Employee*], [*Days*], [*Prorated*], [*OT*], [*Reimb*], [*Amount*],
  ),
  {rows}
)

#v(10pt)

#align(right)[
  #text(size: 13pt, weight: "bold")[Total: AED {amount}]
]

{warning}
{exceptions}

#v(14pt)
#line(length: 100%, stroke: 0.3pt + muted)
#v(4pt)
#text(size: 7.5pt, fill: muted)[
  Audit hash: {hash}  ·  Generated by TIA (Touchless Invoice Agent) · Mock ERP output
]
"""


def _row_line(li: dict) -> str:
    cells = [
        _esc(li.get("emp_id")),
        _esc(li.get("employee_name")),
        _esc(li.get("days_worked")),
        _num(li.get("prorated")),
        _num(li.get("ot_amount")),
        _num(li.get("reimbursements")),
        _num(li.get("amount")),
    ]
    return ", ".join(f"[{c}]" for c in cells) + ","


def _warning_block(invoice: dict) -> str:
    if not invoice.get("requires_finance_approval"):
        return ""
    return (
        "#v(8pt)\n"
        '#block(fill: rgb("#fff4ec"), stroke: 0.6pt + rgb("{brand}"), '
        "inset: 10pt, radius: 2pt, width: 100%)[\n"
        '  #text(fill: rgb("{brand}"), weight: "bold")[⚠ Above client threshold] — '
        "requires Finance approval before dispatch.\n"
        "]\n"
    ).replace("{brand}", BRAND_HEX)


def _exceptions_block(invoice: dict) -> str:
    exs = invoice.get("exceptions") or []
    if not exs:
        return ""
    lines = "\n".join(
        f"  - {_esc(ex.get('employee_name'))}: {_esc(ex.get('reason'))}" for ex in exs
    )
    return (
        f"\n#v(8pt)\n"
        f"*Held for review ({len(exs)} row" + ("s" if len(exs) != 1 else "") + ")*\n"
        f"{lines}\n"
    )


def render_invoice(invoice: dict, invoice_id: str) -> str:
    audit = _audit_hash(invoice)
    rows = "\n  ".join(_row_line(li) for li in invoice.get("line_items", []))
    source = _TEMPLATE.format(
        inv_id=_esc(invoice_id),
        brand=BRAND_HEX,
        client=_esc(invoice.get("client_name") or invoice.get("client_code") or "—"),
        period=_esc(invoice.get("period") or "—"),
        amount=_num(invoice.get("amount")),
        rows=rows or "[—], [no line items], [], [], [], [], [],",
        warning=_warning_block(invoice),
        exceptions=_exceptions_block(invoice),
        hash=audit,
    )
    typ_path = Path(STAGING_DIR) / f"invoice_{invoice_id}.typ"
    pdf_path = Path(STAGING_DIR) / f"invoice_{invoice_id}.pdf"
    typ_path.write_text(source, encoding="utf-8")
    typst.compile(str(typ_path), output=str(pdf_path))
    return str(pdf_path)


def _demo() -> None:
    inv = {
        "client_name": "Emaar",
        "client_code": "CL002",
        "period": "June 2026",
        "currency": "AED",
        "amount": 12345.67,
        "requires_finance_approval": True,
        "line_items": [
            {
                "emp_id": "EMP10001",
                "employee_name": "Carlos Smith",
                "days_worked": 22,
                "prorated": 10000.0,
                "ot_amount": 500.0,
                "reimbursements": 0.0,
                "amount": 12075.0,
            },
        ],
        "exceptions": [{"employee_name": "Aisha Al Zaabi", "reason": "ambiguous match"}],
    }
    out = render_invoice(inv, "demo-001")
    assert Path(out).exists() and Path(out).stat().st_size > 1000, out
    print("typst invoice rendered:", out, Path(out).stat().st_size, "bytes")


if __name__ == "__main__":
    _demo()
