"""Invoice PDF rendering via fpdf2 (pure Python, no system libs).

Typst is the production renderer in the architecture; fpdf2 keeps the demo zero-dependency.
Every PDF carries an audit hash in the footer for tamper-evidence.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from fpdf import FPDF

from ..config import STAGING_DIR

BRAND = (217, 83, 30)  # TASC orange-red


def _audit_hash(invoice: dict) -> str:
    payload = json.dumps(invoice, sort_keys=True, default=str).encode()
    return hashlib.sha256(payload).hexdigest()[:16]


def _t(s) -> str:
    """fpdf2 core fonts are latin-1; drop/replace anything outside it."""
    return str(s).encode("latin-1", "replace").decode("latin-1")


def render_invoice(invoice: dict, invoice_id: str) -> str:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_fill_color(*BRAND)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 14, "  TASC Outsourcing  -  Tax Invoice", fill=True, ln=1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, _t(f"Invoice: {invoice_id}"), ln=1)
    pdf.cell(0, 7, _t(f"Client: {invoice.get('client_name') or invoice.get('client_code')}"), ln=1)
    pdf.cell(
        0, 7, _t(f"Period: {invoice.get('period')}    Currency: {invoice.get('currency')}"), ln=1
    )
    pdf.ln(4)

    # table header
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(235, 235, 235)
    cols = [
        ("Emp ID", 22),
        ("Employee", 44),
        ("Days", 14),
        ("Prorated", 26),
        ("OT", 18),
        ("Reimb", 20),
        ("Amount", 28),
    ]
    for name, w in cols:
        pdf.cell(w, 8, name, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    for li in invoice.get("line_items", []):
        pdf.cell(22, 7, _t(li["emp_id"]), border=1)
        pdf.cell(44, 7, _t(str(li["employee_name"])[:26]), border=1)
        pdf.cell(14, 7, str(li["days_worked"]), border=1)
        pdf.cell(26, 7, f"{li['prorated']:.2f}", border=1)
        pdf.cell(18, 7, f"{li['ot_amount']:.2f}", border=1)
        pdf.cell(20, 7, f"{li['reimbursements']:.2f}", border=1)
        pdf.cell(28, 7, f"{li['amount']:.2f}", border=1)
        pdf.ln()

    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 9, f"TOTAL: {invoice.get('currency')} {invoice.get('amount'):.2f}", ln=1)

    if invoice.get("requires_finance_approval"):
        pdf.set_text_color(*BRAND)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "** Above client threshold - requires Finance approval **", ln=1)
        pdf.set_text_color(0, 0, 0)

    if invoice.get("exceptions"):
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, f"Exceptions held for review: {len(invoice['exceptions'])}", ln=1)
        pdf.set_font("Helvetica", "", 8)
        for ex in invoice["exceptions"]:
            pdf.cell(0, 5, _t(f"  - {ex['employee_name']}: {ex['reason']}"), ln=1)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(
        0, 5, f"Audit hash: {_audit_hash(invoice)}  |  Generated by TIA. Mock ERP output.", ln=1
    )

    out = Path(STAGING_DIR) / f"invoice_{invoice_id}.pdf"
    pdf.output(str(out))
    return str(out)
