"""baseline schema

Revision ID: 31bb83339cb0
Revises: 
Create Date: 2026-07-01 17:30:35.335903
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bb83339cb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_at'), 'chat_messages', ['at'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender'), 'chat_messages', ['sender'], unique=False)
    op.create_table('clients',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('currency_default', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('corrections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('timesheet_id', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('by_user', sa.String(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_timesheet_id'), 'corrections', ['timesheet_id'], unique=False)
    op.create_table('doc_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('staging_path', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('doc_class', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('parent_doc_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_doc_id'], ['doc_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'source_channel', 'uploaded_by', name='uq_doc_content_per_sender')
    )
    op.create_index(op.f('ix_doc_assets_content_hash'), 'doc_assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_doc_assets_parent_doc_id'), 'doc_assets', ['parent_doc_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('entity_kind', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_events_idem')
    )
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_entity_kind'), 'events', ['entity_kind'], unique=False)
    op.create_index(op.f('ix_events_hash'), 'events', ['hash'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('sac_code', sa.String(), nullable=True),
    sa.Column('markup_pct', sa.Float(), nullable=False),
    sa.Column('max_ot_pct', sa.Float(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('billing_cadence', sa.String(), nullable=False),
    sa.Column('approver_name', sa.String(), nullable=True),
    sa.Column('approver_email', sa.String(), nullable=True),
    sa.Column('authorized_emp_ids', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_code'], ['clients.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_client_code'), 'contracts', ['client_code'], unique=False)
    op.create_table('employees',
    sa.Column('emp_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('date_of_joining', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('housing', sa.Float(), nullable=False),
    sa.Column('transport', sa.Float(), nullable=False),
    sa.Column('food', sa.Float(), nullable=False),
    sa.Column('phone', sa.Float(), nullable=False),
    sa.Column('total_ctc', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_code'], ['clients.code'], ),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employees_client_code'), 'employees', ['client_code'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raised_by', sa.String(), nullable=True),
    sa.Column('raised_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('thread', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_code'], ['clients.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_client_code'), 'queries', ['client_code'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('client_code', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('routing', sa.String(), nullable=True),
    sa.Column('confidence_calibrated', sa.Float(), nullable=True),
    sa.Column('hitl_reason', sa.String(), nullable=True),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('resolved_rows', sa.JSON(), nullable=False),
    sa.Column('validations', sa.JSON(), nullable=False),
    sa.Column('match_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('needs_review_reason', sa.Text(), nullable=True),
    sa.Column('needs_review_since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['doc_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheets_status'), 'timesheets', ['status'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timesheet_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('source_block_id', sa.String(), nullable=True),
    sa.Column('raw_confidence', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_timesheet_id'), 'hypotheses', ['timesheet_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timesheet_id', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dispatch_idempotency_key', sa.String(), nullable=True),
    sa.Column('dispatch_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('invoice_sequence_no', sa.String(), nullable=True),
    sa.Column('supplier_trn', sa.String(), nullable=True),
    sa.Column('customer_trn', sa.String(), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('total_excl_vat', sa.Float(), nullable=False),
    sa.Column('total_incl_vat', sa.Float(), nullable=False),
    sa.Column('sac_code', sa.String(), nullable=True),
    sa.Column('place_of_supply', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('client_approval_status', sa.String(), nullable=True),
    sa.Column('client_approved_at', sa.DateTime(), nullable=True),
    sa.Column('client_approval_reason', sa.Text(), nullable=True),
    sa.Column('rule_results', sa.JSON(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by', sa.String(), nullable=True),
    sa.Column('voided_reason_code', sa.String(), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.Column('credit_note_sequence_no', sa.String(), nullable=True),
    sa.Column('credit_note_issued_at', sa.DateTime(), nullable=True),
    sa.Column('credit_note_issued_by', sa.String(), nullable=True),
    sa.Column('credit_note_reason_code', sa.String(), nullable=True),
    sa.Column('credit_note_reason_text', sa.Text(), nullable=True),
    sa.Column('credit_note_article_refs', sa.JSON(), nullable=True),
    sa.Column('credit_note_amount', sa.Float(), nullable=True),
    sa.Column('credit_note_disputed_hours', sa.Float(), nullable=True),
    sa.Column('adjustment_type', sa.String(), nullable=True),
    sa.Column('replaces_invoice_id', sa.String(), nullable=True),
    sa.Column('superseded_by_invoice_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['replaces_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_idempotency_key')
    )
    op.create_index(op.f('ix_invoices_client_code'), 'invoices', ['client_code'], unique=False)
    op.create_index(op.f('ix_invoices_contract_id'), 'invoices', ['contract_id'], unique=False)
    op.create_index(op.f('ix_invoices_credit_note_sequence_no'), 'invoices', ['credit_note_sequence_no'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_sequence_no'), 'invoices', ['invoice_sequence_no'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_timesheet_id'), 'invoices', ['timesheet_id'], unique=False)
    op.create_table('payroll',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('emp_id', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('housing', sa.Float(), nullable=False),
    sa.Column('transport', sa.Float(), nullable=False),
    sa.Column('food', sa.Float(), nullable=False),
    sa.Column('phone', sa.Float(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('ot_hours', sa.Float(), nullable=False),
    sa.Column('ot_amount', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_client_code'), 'payroll', ['client_code'], unique=False)
    op.create_index(op.f('ix_payroll_emp_id'), 'payroll', ['emp_id'], unique=False)
    op.create_index(op.f('ix_payroll_period'), 'payroll', ['period'], unique=False)
    op.create_table('rate_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('labor_category', sa.String(), nullable=False),
    sa.Column('regular_rate', sa.Float(), nullable=False),
    sa.Column('ot_rate', sa.Float(), nullable=False),
    sa.Column('night_rate', sa.Float(), nullable=False),
    sa.Column('weekend_rate', sa.Float(), nullable=False),
    sa.Column('holiday_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_cards_contract_id'), 'rate_cards', ['contract_id'], unique=False)
    op.create_table('sows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('deliverable', sa.String(), nullable=False),
    sa.Column('hours_expected', sa.Float(), nullable=False),
    sa.Column('hours_consumed', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sows_contract_id'), 'sows', ['contract_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('client_code', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_by', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_code'], ['clients.code'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_payments_client_code'), 'payments', ['client_code'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_code'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sows_contract_id'), table_name='sows')
    op.drop_table('sows')
    op.drop_index(op.f('ix_rate_cards_contract_id'), table_name='rate_cards')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_payroll_period'), table_name='payroll')
    op.drop_index(op.f('ix_payroll_emp_id'), table_name='payroll')
    op.drop_index(op.f('ix_payroll_client_code'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_index(op.f('ix_invoices_timesheet_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_sequence_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_credit_note_sequence_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_contract_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_code'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_hypotheses_timesheet_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_timesheets_status'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_queries_client_code'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_client_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_contracts_client_code'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_events_hash'), table_name='events')
    op.drop_index(op.f('ix_events_entity_kind'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_doc_assets_parent_doc_id'), table_name='doc_assets')
    op.drop_index(op.f('ix_doc_assets_content_hash'), table_name='doc_assets')
    op.drop_table('doc_assets')
    op.drop_index(op.f('ix_corrections_timesheet_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_table('clients')
    op.drop_index(op.f('ix_chat_messages_sender'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
